version: '3.1'

services:
  app:
    image: sonlexqt/node-app
    build: .
    ports:
      - "4000:4000"
    volumes:
      - "./:/usr/src/app"
      - "/usr/src/app/node_modules/"
    depends_on:
      - mongo
      - postgres
    environment:
      WAIT_HOSTS: mongo:27017, postgres:5432

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
  
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: example
      POSTGRES_DB: dsv
